# Generated by Django 4.2.3 on 2024-05-14 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ticket_status_alter_ticket_description_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='group',
            field=models.CharField(choices=[('spitamen', 'Spitamen'), ('sbt', 'Sbt'), ('matin', 'Matin'), ('ssb', 'Ssb'), ('sarvat', 'Sarvat'), ('vasl', 'Vasl')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
