# Generated by Django 4.2.3 on 2024-06-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ticket_visible_to_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='visible_to_groups',
        ),
    ]
