# Generated by Django 4.2.3 on 2024-06-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_ticket_visible_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by_group',
            field=models.CharField(blank=True, choices=[('spitamen', 'Spitamen'), ('sbt', 'Sbt'), ('matin', 'Matin'), ('ssb', 'Ssb'), ('sarvat', 'Sarvat'), ('vasl', 'Vasl')], max_length=20, null=True),
        ),
    ]
